Config = {}

-- Menu open key (default: F6)
Config.OpenKey = 'F6'

-- ================= PERSISTENCE =================
-- Every blip/marker/checkpoint created through the menu is saved server-side
-- to this JSON file (via SaveResourceFile) and reloaded automatically when
-- the resource/server restarts. Nothing here depends on a database, so it
-- works out of the box on any server.
Config.Persistence = {
    file = 'dzblip_points.json', -- stored inside this resource's own folder
}

-- ================= ACCESS MODE =================
-- One switch controls who can open the menu and place/remove/export points.
-- Change ONLY this line to flip between the two modes:
--
--   Config.AccessMode = 'everyone'  -> anyone connected can use it
--   Config.AccessMode = 'admin'     -> only players granted the ace permission
--                                      below (Config.Permission.ace) can use it
--
-- Framework-agnostic on purpose: instead of checking ESX/QB-Core/QBox admin
-- groups, 'admin' mode uses FiveM's own built-in ACE permission system, so it
-- works the same whether the server runs ESX, QB, QBox, or no framework at all.
-- To use 'admin' mode, also grant the ace in server.cfg, e.g.:
--   add_ace group.admin dzblip.use allow
--   add_principal identifier.license:xxxxxxxx group.admin
Config.AccessMode = 'everyone' -- 'everyone' or 'admin'

Config.Permission = {
    ace = 'dzblip.use',
}

-- ================= DEFAULTS =================
-- Starting values the menu opens with for scale/color/radius fields, for
-- ALL THREE tabs (Blips, Markers, Checkpoints). These are just a starting
-- point - every value below is still fully adjustable per-item in the menu
-- itself (sliders + exact number inputs), this only controls what it's set
-- to before you touch anything.
Config.Defaults = {
    blipScale = 1.0,

    markerColor = { r = 255, g = 0, b = 255, a = 150 },
    markerScale = { x = 1.0, y = 1.0, z = 1.0 },

    checkpointColor = { r = 255, g = 0, b = 255, a = 150 },
    checkpointRadius = 5.0, -- <- the "checkpoint radius" default
}

-- ================= BLIP COLORS =================
Config.BlipColors = {
    {id = 0,  name = 'White'},
    {id = 1,  name = 'Red'},
    {id = 2,  name = 'Green'},
    {id = 3,  name = 'Blue (Light)'},
    {id = 4,  name = 'White 2'},
    {id = 5,  name = 'Yellow'},
    {id = 6,  name = 'Light Blue'},
    {id = 7,  name = 'Purple (Dark)'},
    {id = 8,  name = 'Pink'},
    {id = 9,  name = 'Yellowish'},
    {id = 10, name = 'Blue (Dark)'},
    {id = 11, name = 'Teal'},
    {id = 12, name = 'Yellow (Dark)'},
    {id = 17, name = 'Grey (Light)'},
    {id = 21, name = 'Orange'},
    {id = 22, name = 'Green (Light)'},
    {id = 23, name = 'Grey'},
    {id = 25, name = 'Pink (Bright)'},
    {id = 27, name = 'Orange (Bright)'},
    {id = 28, name = 'Blue (Bright)'},
    {id = 38, name = 'Purple'},
    {id = 42, name = 'Grey (Dark)'},
    {id = 47, name = 'Green (Army)'},
    {id = 49, name = 'Purple (Dark 2)'},
    {id = 58, name = 'Red (Bright)'},
    {id = 61, name = 'Grey (Blueish)'},
    {id = 63, name = 'Orange 2'},
    {id = 66, name = 'Green (Dark)'},
    {id = 68, name = 'Yellow (Bright)'},
    {id = 69, name = 'Red (Dark)'},
    {id = 83, name = 'White (Blueish)'},
    {id = 85, name = 'Purple (Bright)'},
}

-- ================= BLIP SPRITES =================
-- Complete list as documented by CitizenFX (docs.fivem.net/docs/game-references/blips), build 3258.
-- Blip image: https://docs-backend.fivem.net/blips/<icon>.png
Config.Blips = {
    {cat = 'General / Map', list = {
        {id = 0, name = 'Higher', icon = 'radar_higher', animated = true},
        {id = 1, name = 'Level', icon = 'radar_level'},
        {id = 2, name = 'Lower', icon = 'radar_lower', animated = true},
        {id = 3, name = 'Police Ped', icon = 'radar_police_ped', animated = true},
        {id = 4, name = 'Wanted Radius', icon = 'radar_wanted_radius'},
        {id = 5, name = 'Area Blip', icon = 'radar_area_blip'},
        {id = 6, name = 'Centre', icon = 'radar_centre'},
        {id = 7, name = 'North', icon = 'radar_north'},
        {id = 8, name = 'Waypoint', icon = 'radar_waypoint'},
        {id = 9, name = 'Radius Blip', icon = 'radar_radius_blip'},
        {id = 10, name = 'Radius Outline Blip', icon = 'radar_radius_outline_blip'},
        {id = 11, name = 'Weapon Higher', icon = 'radar_weapon_higher', animated = true},
        {id = 12, name = 'Weapon Lower', icon = 'radar_weapon_lower', animated = true},
        {id = 13, name = 'Higher Ai', icon = 'radar_higher_ai', animated = true},
        {id = 14, name = 'Lower Ai', icon = 'radar_lower_ai', animated = true},
        {id = 15, name = 'Police Heli Spin', icon = 'radar_police_heli_spin', animated = true},
        {id = 16, name = 'Police Plane Move', icon = 'radar_police_plane_move'},
        {id = 27, name = 'Mp Crew', icon = 'radar_mp_crew'},
        {id = 28, name = 'Mp Friendlies', icon = 'radar_mp_friendlies'},
        {id = 138, name = 'Airport', icon = 'radar_airport'},
        {id = 143, name = 'Objective Blue', icon = 'radar_objective_blue'},
        {id = 144, name = 'Objective Green', icon = 'radar_objective_green'},
        {id = 145, name = 'Objective Red', icon = 'radar_objective_red'},
        {id = 146, name = 'Objective Yellow', icon = 'radar_objective_yellow'},
        {id = 148, name = 'Mp Friend', icon = 'radar_mp_friend'},
        {id = 162, name = 'Poi', icon = 'radar_poi'},
        {id = 163, name = 'Passive', icon = 'radar_passive'},
        {id = 164, name = 'Usingmenu', icon = 'radar_usingmenu'},
        {id = 185, name = 'Centre Red', icon = 'radar_centre_red'},
        {id = 280, name = 'Friend', icon = 'radar_friend'},
        {id = 296, name = 'Friend Darts', icon = 'radar_friend_darts'},
        {id = 297, name = 'Friend Comedyclub', icon = 'radar_friend_comedyclub'},
        {id = 298, name = 'Friend Cinema', icon = 'radar_friend_cinema'},
        {id = 299, name = 'Friend Tennis', icon = 'radar_friend_tennis'},
        {id = 300, name = 'Friend Stripclub', icon = 'radar_friend_stripclub'},
        {id = 301, name = 'Friend Livemusic', icon = 'radar_friend_livemusic'},
        {id = 302, name = 'Friend Golf', icon = 'radar_friend_golf'},
        {id = 365, name = 'Spawn Point Pickup', icon = 'radar_spawn_point_pickup'},
        {id = 395, name = 'Green And Friendly', icon = 'radar_green_and_friendly'},
        {id = 412, name = 'Mp Crew', icon = 'radar_mp_crew'},
        {id = 416, name = 'Rp', icon = 'radar_rp'},
        {id = 417, name = 'Level Inside', icon = 'radar_level_inside'},
        {id = 425, name = 'Centre Stroke', icon = 'radar_centre_stroke'},
        {id = 443, name = 'Edge Pointer', icon = 'radar_edge_pointer'},
        {id = 482, name = 'Area Outline Blip', icon = 'radar_area_outline_blip'},
        {id = 570, name = 'Tf Checkpoint', icon = 'radar_tf_checkpoint'},
        {id = 605, name = 'Nhp Starterpack', icon = 'radar_nhp_starterpack'},
    }},
    {cat = 'Police / Law Enforcement', list = {
        {id = 41, name = 'Police', icon = 'radar_police', animated = true},
        {id = 42, name = 'Police Chase', icon = 'radar_police_chase', animated = true},
        {id = 43, name = 'Police Heli', icon = 'radar_police_heli'},
        {id = 47, name = 'Snitch', icon = 'radar_snitch'},
        {id = 50, name = 'Crim Carsteal', icon = 'radar_crim_carsteal'},
        {id = 51, name = 'Crim Drugs', icon = 'radar_crim_drugs'},
        {id = 52, name = 'Crim Holdups', icon = 'radar_crim_holdups'},
        {id = 54, name = 'Crim Player', icon = 'radar_crim_player'},
        {id = 56, name = 'Cop Patrol', icon = 'radar_cop_patrol'},
        {id = 57, name = 'Cop Player', icon = 'radar_cop_player'},
        {id = 58, name = 'Crim Wanted', icon = 'radar_crim_wanted'},
        {id = 60, name = 'Police Station', icon = 'radar_police_station'},
        {id = 105, name = 'Fbi Heist', icon = 'radar_fbi_heist'},
        {id = 106, name = 'Fbi Officers Strand', icon = 'radar_fbi_officers_strand'},
        {id = 128, name = 'Gang Cops', icon = 'radar_gang_cops'},
        {id = 133, name = 'Snitch Red', icon = 'radar_snitch_red'},
        {id = 134, name = 'Crim Cuff Keys', icon = 'radar_crim_cuff_keys'},
        {id = 137, name = 'Police Station Blue', icon = 'radar_police_station_blue'},
        {id = 139, name = 'Crim Saved Vehicle', icon = 'radar_crim_saved_vehicle'},
        {id = 171, name = 'Gang Cops Partner', icon = 'radar_gang_cops_partner'},
        {id = 186, name = 'Handcuff Keys Bikers', icon = 'radar_handcuff_keys_bikers'},
        {id = 187, name = 'Handcuff Keys Vagos', icon = 'radar_handcuff_keys_vagos'},
        {id = 188, name = 'Handcuffs Closed Bikers', icon = 'radar_handcuffs_closed_bikers'},
        {id = 189, name = 'Handcuffs Closed Vagos', icon = 'radar_handcuffs_closed_vagos'},
        {id = 231, name = 'Driving Cops', icon = 'radar_driving_cops'},
        {id = 233, name = 'Gang Cops Highlight', icon = 'radar_gang_cops_highlight'},
        {id = 234, name = 'Shield Bikers', icon = 'radar_shield_bikers'},
        {id = 235, name = 'Shield Cops', icon = 'radar_shield_cops'},
        {id = 236, name = 'Shield Vagos', icon = 'radar_shield_vagos'},
        {id = 237, name = 'Custody Bikers', icon = 'radar_custody_bikers'},
        {id = 238, name = 'Custody Vagos', icon = 'radar_custody_vagos'},
        {id = 252, name = 'Playerstate Arrested', icon = 'radar_playerstate_arrested'},
        {id = 253, name = 'Playerstate Custody', icon = 'radar_playerstate_custody'},
        {id = 285, name = 'Custody Dropoff', icon = 'radar_custody_dropoff'},
        {id = 286, name = 'Onmission Cops', icon = 'radar_onmission_cops'},
        {id = 289, name = 'Crim Carsteal Cops', icon = 'radar_crim_carsteal_cops'},
        {id = 290, name = 'Crim Carsteal Bikers', icon = 'radar_crim_carsteal_bikers'},
        {id = 291, name = 'Crim Carsteal Vagos', icon = 'radar_crim_carsteal_vagos'},
        {id = 334, name = 'Mission Cops 1', icon = 'radar_mission_cops_1'},
        {id = 335, name = 'Mission Cops 1to2', icon = 'radar_mission_cops_1to2'},
        {id = 336, name = 'Mission Cops 2', icon = 'radar_mission_cops_2'},
        {id = 337, name = 'Mission Cops 2to4', icon = 'radar_mission_cops_2to4'},
        {id = 338, name = 'Mission Cops 2to8', icon = 'radar_mission_cops_2to8'},
        {id = 339, name = 'Mission Cops 2to12', icon = 'radar_mission_cops_2to12'},
        {id = 340, name = 'Mission Cops 2to16', icon = 'radar_mission_cops_2to16'},
        {id = 526, name = 'Police Station Dropoff', icon = 'radar_police_station_dropoff'},
        {id = 672, name = 'Cop Car', icon = 'radar_cop_car'},
        {id = 815, name = 'Ped R', icon = 'radar_ped_r'},
        {id = 816, name = 'Ped E', icon = 'radar_ped_e'},
        {id = 818, name = 'Patriot3', icon = 'radar_patriot3'},
        {id = 893, name = 'Bail Bonds Office', icon = 'radar_bail_bonds_office'},
    }},
    {cat = 'Emergency & Public Services', list = {
        {id = 61, name = 'Hospital', icon = 'radar_hospital'},
        {id = 68, name = 'Tow Truck', icon = 'radar_tow_truck'},
        {id = 70, name = 'Illegal Parking', icon = 'radar_illegal_parking'},
        {id = 71, name = 'Barber', icon = 'radar_barber'},
        {id = 72, name = 'Car Mod Shop', icon = 'radar_car_mod_shop'},
        {id = 73, name = 'Clothes Store', icon = 'radar_clothes_store'},
        {id = 75, name = 'Tattoo', icon = 'radar_tattoo'},
        {id = 100, name = 'Car Wash', icon = 'radar_car_wash'},
        {id = 317, name = 'Tow', icon = 'radar_tow'},
        {id = 321, name = 'Firetruck', icon = 'radar_firetruck'},
        {id = 767, name = 'Control Tower', icon = 'radar_control_tower'},
        {id = 817, name = 'Payphone', icon = 'radar_payphone'},
        {id = 843, name = 'Downtown Cab', icon = 'radar_downtown_cab'},
        {id = 931, name = 'Car Wash Business', icon = 'radar_car_wash_business'},
        {id = 932, name = 'Car Wash Business For Sale', icon = 'radar_car_wash_business_for_sale'},
        {id = 933, name = 'Car Wash Business Attention', icon = 'radar_car_wash_business_attention'},
    }},
    {cat = 'Heists & Missions', list = {
        {id = 48, name = 'Planning Locations', icon = 'radar_planning_locations'},
        {id = 59, name = 'Heist', icon = 'radar_heist'},
        {id = 80, name = 'Jewelry Heist', icon = 'radar_jewelry_heist'},
        {id = 96, name = 'Biolab Heist', icon = 'radar_biolab_heist'},
        {id = 104, name = 'Docks Heist', icon = 'radar_docks_heist'},
        {id = 107, name = 'Finale Bank Heist', icon = 'radar_finale_bank_heist'},
        {id = 113, name = 'Nice House Heist', icon = 'radar_nice_house_heist'},
        {id = 118, name = 'Rural Bank Heist', icon = 'radar_rural_bank_heist'},
        {id = 281, name = 'Mission 2to4', icon = 'radar_mission_2to4'},
        {id = 282, name = 'Mission 2to8', icon = 'radar_mission_2to8'},
        {id = 283, name = 'Mission 2to12', icon = 'radar_mission_2to12'},
        {id = 284, name = 'Mission 2to16', icon = 'radar_mission_2to16'},
        {id = 287, name = 'Onmission Lost', icon = 'radar_onmission_lost'},
        {id = 288, name = 'Onmission Vagos', icon = 'radar_onmission_vagos'},
        {id = 294, name = 'Mission 1', icon = 'radar_mission_1'},
        {id = 295, name = 'Mission 2', icon = 'radar_mission_2'},
        {id = 312, name = 'Mission 1to2', icon = 'radar_mission_1to2'},
        {id = 327, name = 'Mission Bikers 1', icon = 'radar_mission_bikers_1'},
        {id = 328, name = 'Mission Bikers 1to2', icon = 'radar_mission_bikers_1to2'},
        {id = 329, name = 'Mission Bikers 2', icon = 'radar_mission_bikers_2'},
        {id = 330, name = 'Mission Bikers 2to4', icon = 'radar_mission_bikers_2to4'},
        {id = 331, name = 'Mission Bikers 2to8', icon = 'radar_mission_bikers_2to8'},
        {id = 332, name = 'Mission Bikers 2to12', icon = 'radar_mission_bikers_2to12'},
        {id = 333, name = 'Mission Bikers 2to16', icon = 'radar_mission_bikers_2to16'},
        {id = 341, name = 'Mission Vagos 1', icon = 'radar_mission_vagos_1'},
        {id = 342, name = 'Mission Vagos 1to2', icon = 'radar_mission_vagos_1to2'},
        {id = 343, name = 'Mission Vagos 2', icon = 'radar_mission_vagos_2'},
        {id = 344, name = 'Mission Vagos 2to4', icon = 'radar_mission_vagos_2to4'},
        {id = 345, name = 'Mission Vagos 2to8', icon = 'radar_mission_vagos_2to8'},
        {id = 346, name = 'Mission Vagos 2to12', icon = 'radar_mission_vagos_2to12'},
        {id = 347, name = 'Mission Vagos 2to16', icon = 'radar_mission_vagos_2to16'},
        {id = 363, name = 'Heist Prep', icon = 'radar_heist_prep'},
        {id = 428, name = 'Mp Heist', icon = 'radar_mp_heist'},
        {id = 765, name = 'Island Heist Prep', icon = 'radar_island_heist_prep'},
        {id = 783, name = 'Car Robbery Board', icon = 'radar_car_robbery_board'},
        {id = 784, name = 'Car Robbery Prep', icon = 'radar_car_robbery_prep'},
        {id = 788, name = 'Securoserv', icon = 'radar_securoserv'},
        {id = 796, name = 'Heist Diamond', icon = 'radar_heist_diamond'},
        {id = 797, name = 'Heist Doomsday', icon = 'radar_heist_doomsday'},
        {id = 798, name = 'Heist Island', icon = 'radar_heist_island'},
        {id = 803, name = 'Heist Island Unavailable', icon = 'radar_heist_island_unavailable'},
        {id = 804, name = 'Heist Diamond Unavailable', icon = 'radar_heist_diamond_unavailable'},
        {id = 805, name = 'Heist Doomsday Unavailable', icon = 'radar_heist_doomsday_unavailable'},
        {id = 837, name = 'Clubhouse Contract', icon = 'radar_clubhouse_contract'},
        {id = 838, name = 'Agent Ulp', icon = 'radar_agent_ulp'},
        {id = 840, name = 'Acid Lab', icon = 'radar_acid_lab'},
        {id = 845, name = 'Stash House', icon = 'radar_stash_house'},
        {id = 852, name = 'Acid Lab Tent', icon = 'radar_acid_lab_tent'},
        {id = 868, name = 'Robbery Prep Equipment', icon = 'radar_robbery_prep_equipment'},
        {id = 869, name = 'Robbery Prep Overlay', icon = 'radar_robbery_prep_overlay'},
        {id = 878, name = 'Casino Prep', icon = 'radar_casino_prep'},
        {id = 879, name = 'Planning Wall', icon = 'radar_planning_wall'},
    }},
    {cat = 'Vehicles / Transport', list = {
        {id = 64, name = 'Helicopter', icon = 'radar_helicopter'},
        {id = 130, name = 'Gang Bikers', icon = 'radar_gang_bikers'},
        {id = 178, name = 'Gang Bikers Highlight', icon = 'radar_gang_bikers_highlight'},
        {id = 181, name = 'Property Takeover Bikers', icon = 'radar_property_takeover_bikers'},
        {id = 225, name = 'Gang Vehicle', icon = 'radar_gang_vehicle'},
        {id = 226, name = 'Gang Vehicle Bikers', icon = 'radar_gang_vehicle_bikers'},
        {id = 227, name = 'Gang Vehicle Cops', icon = 'radar_gang_vehicle_cops'},
        {id = 228, name = 'Gang Vehicle Vagos', icon = 'radar_gang_vehicle_vagos'},
        {id = 230, name = 'Driving Bikers', icon = 'radar_driving_bikers'},
        {id = 307, name = 'Plane Drop', icon = 'radar_plane_drop'},
        {id = 308, name = 'Sub', icon = 'radar_sub'},
        {id = 324, name = 'Submarine', icon = 'radar_submarine'},
        {id = 325, name = 'Chinook', icon = 'radar_chinook'},
        {id = 326, name = 'Getaway Car', icon = 'radar_getaway_car'},
        {id = 348, name = 'Gang Bike', icon = 'radar_gang_bike'},
        {id = 374, name = 'Business', icon = 'radar_business'},
        {id = 375, name = 'Business For Sale', icon = 'radar_business_for_sale'},
        {id = 376, name = 'Race Bike', icon = 'radar_race_bike'},
        {id = 380, name = 'Vehicle Deathmatch', icon = 'radar_vehicle_deathmatch'},
        {id = 401, name = 'Blimp', icon = 'radar_blimp'},
        {id = 404, name = 'Dinghy', icon = 'radar_dinghy'},
        {id = 410, name = 'Boat', icon = 'radar_boat'},
        {id = 421, name = 'Tank', icon = 'radar_tank'},
        {id = 423, name = 'Player Plane', icon = 'radar_player_plane'},
        {id = 424, name = 'Player Jet', icon = 'radar_player_jet'},
        {id = 427, name = 'Player Boat', icon = 'radar_player_boat'},
        {id = 455, name = 'Yacht', icon = 'radar_yacht'},
        {id = 460, name = 'Turreted Limo', icon = 'radar_turreted_limo'},
        {id = 462, name = 'Yacht Location', icon = 'radar_yacht_location'},
        {id = 471, name = 'Seashark', icon = 'radar_seashark'},
        {id = 477, name = 'Truck', icon = 'radar_truck'},
        {id = 479, name = 'Trailer', icon = 'radar_trailer'},
        {id = 481, name = 'Cargobob', icon = 'radar_cargobob'},
        {id = 492, name = 'Biker Clubhouse', icon = 'radar_biker_clubhouse'},
        {id = 493, name = 'Biker Caged In', icon = 'radar_biker_caged_in'},
        {id = 494, name = 'Biker Turf War', icon = 'radar_biker_turf_war'},
        {id = 495, name = 'Biker Joust', icon = 'radar_biker_joust'},
        {id = 512, name = 'Quad', icon = 'radar_quad'},
        {id = 513, name = 'Bus', icon = 'radar_bus'},
        {id = 524, name = 'Warehouse Vehicle', icon = 'radar_warehouse_vehicle'},
        {id = 528, name = 'Ex Vech 1', icon = 'radar_ex_vech_1'},
        {id = 529, name = 'Ex Vech 2', icon = 'radar_ex_vech_2'},
        {id = 530, name = 'Ex Vech 3', icon = 'radar_ex_vech_3'},
        {id = 531, name = 'Ex Vech 4', icon = 'radar_ex_vech_4'},
        {id = 532, name = 'Ex Vech 5', icon = 'radar_ex_vech_5'},
        {id = 533, name = 'Ex Vech 6', icon = 'radar_ex_vech_6'},
        {id = 534, name = 'Ex Vech 7', icon = 'radar_ex_vech_7'},
        {id = 616, name = 'Bat Truck', icon = 'radar_bat_truck'},
        {id = 631, name = 'Bat Pbus', icon = 'radar_bat_pbus'},
        {id = 638, name = 'Blimp 2', icon = 'radar_blimp_2'},
        {id = 639, name = 'Oppressor 2', icon = 'radar_oppressor_2'},
        {id = 661, name = 'Arena Deathbike', icon = 'radar_arena_deathbike'},
        {id = 668, name = 'Arena Slamvan', icon = 'radar_arena_slamvan'},
        {id = 677, name = 'Shipping Container', icon = 'radar_shipping_container'},
        {id = 724, name = 'Limo', icon = 'radar_limo'},
        {id = 728, name = 'Swap Car', icon = 'radar_swap_car'},
        {id = 734, name = 'Snow Truck', icon = 'radar_snow_truck'},
        {id = 735, name = 'Buggy 1', icon = 'radar_buggy_1'},
        {id = 736, name = 'Buggy 2', icon = 'radar_buggy_2'},
        {id = 742, name = 'Rc Tank', icon = 'radar_rc_tank'},
        {id = 746, name = 'Mini Sub', icon = 'radar_mini_sub'},
        {id = 747, name = 'Kart Retro', icon = 'radar_kart_retro'},
        {id = 748, name = 'Kart Modern', icon = 'radar_kart_modern'},
        {id = 749, name = 'Military Quad', icon = 'radar_military_quad'},
        {id = 750, name = 'Military Truck', icon = 'radar_military_truck'},
        {id = 752, name = 'Ufo', icon = 'radar_ufo'},
        {id = 754, name = 'Dinghy2', icon = 'radar_dinghy2'},
        {id = 755, name = 'Patrol Boat', icon = 'radar_patrol_boat'},
        {id = 757, name = 'Squadee', icon = 'radar_squadee'},
        {id = 758, name = 'Folding Wing Jet', icon = 'radar_folding_wing_jet'},
        {id = 760, name = 'Sub2', icon = 'radar_sub2'},
        {id = 773, name = 'Sub Controls', icon = 'radar_sub_controls'},
        {id = 774, name = 'Sub Periscope', icon = 'radar_sub_periscope'},
        {id = 775, name = 'Sub Missile', icon = 'radar_sub_missile'},
        {id = 777, name = 'Car Meet', icon = 'radar_car_meet'},
        {id = 778, name = 'Car Test Area', icon = 'radar_car_test_area'},
        {id = 781, name = 'Prize Car', icon = 'radar_prize_car'},
        {id = 782, name = 'Test Car', icon = 'radar_test_car'},
        {id = 787, name = 'Car Meet Organiser', icon = 'radar_car_meet_organiser'},
        {id = 791, name = 'Trailer Ramp', icon = 'radar_trailer_ramp'},
        {id = 794, name = 'Export Vehicle', icon = 'radar_export_vehicle'},
        {id = 795, name = 'Train', icon = 'radar_train'},
        {id = 799, name = 'Slamvan2', icon = 'radar_slamvan2'},
        {id = 800, name = 'Crusader', icon = 'radar_crusader'},
        {id = 810, name = 'Vehicle For Sale', icon = 'radar_vehicle_for_sale'},
        {id = 811, name = 'Van Keys', icon = 'radar_van_keys'},
        {id = 821, name = 'Granger2', icon = 'radar_granger2'},
        {id = 825, name = 'Buffalo4', icon = 'radar_buffalo4'},
        {id = 827, name = 'Biker Bar', icon = 'radar_biker_bar'},
        {id = 830, name = 'Luxury Car Showroom', icon = 'radar_luxury_car_showroom'},
        {id = 831, name = 'Car Showroom', icon = 'radar_car_showroom'},
        {id = 832, name = 'Car Showroom Simeon', icon = 'radar_car_showroom_simeon'},
        {id = 846, name = 'Tractor', icon = 'radar_tractor'},
        {id = 850, name = 'Duffel Bag', icon = 'radar_duffel_bag'},
        {id = 851, name = 'Oil Tanker', icon = 'radar_oil_tanker'},
        {id = 853, name = 'Van Burrito', icon = 'radar_van_burrito'},
        {id = 859, name = 'Bicycle', icon = 'radar_bicycle'},
        {id = 860, name = 'Bicycle Trial', icon = 'radar_bicycle_trial'},
        {id = 862, name = 'Conada2', icon = 'radar_conada2'},
        {id = 882, name = 'Train Signals Green', icon = 'radar_train_signals_green'},
        {id = 883, name = 'Train Signals Red', icon = 'radar_train_signals_red'},
        {id = 890, name = 'Aircraft Carrier', icon = 'radar_aircraft_carrier'},
        {id = 905, name = 'Cargobob Ch53', icon = 'radar_cargobob_ch53'},
        {id = 911, name = 'Cargo Ship', icon = 'radar_cargo_ship'},
        {id = 912, name = 'Submarine Missile', icon = 'radar_submarine_missile'},
        {id = 913, name = 'Propeller Engine', icon = 'radar_propeller_engine'},
        {id = 916, name = 'Plane Duster2', icon = 'radar_plane_duster2'},
        {id = 917, name = 'Plane Titan2', icon = 'radar_plane_titan2'},
    }},
    {cat = 'Business / Money / Property', list = {
        {id = 176, name = 'Property Takeover', icon = 'radar_property_takeover'},
        {id = 182, name = 'Property Takeover Cops', icon = 'radar_property_takeover_cops'},
        {id = 183, name = 'Property Takeover Vagos', icon = 'radar_property_takeover_vagos'},
        {id = 267, name = 'Property', icon = 'radar_property'},
        {id = 272, name = 'Cash Pickup', icon = 'radar_cash_pickup'},
        {id = 276, name = 'Cash Lost', icon = 'radar_cash_lost'},
        {id = 277, name = 'Cash Vagos', icon = 'radar_cash_vagos'},
        {id = 278, name = 'Cash Cops', icon = 'radar_cash_cops'},
        {id = 350, name = 'Property For Sale', icon = 'radar_property_for_sale'},
        {id = 351, name = 'Gang Attack Package', icon = 'radar_gang_attack_package'},
        {id = 356, name = 'Dock', icon = 'radar_dock'},
        {id = 357, name = 'Garage', icon = 'radar_garage'},
        {id = 359, name = 'Hangar', icon = 'radar_hangar'},
        {id = 369, name = 'Garage For Sale', icon = 'radar_garage_for_sale'},
        {id = 370, name = 'Helipad For Sale', icon = 'radar_helipad_for_sale'},
        {id = 371, name = 'Dock For Sale', icon = 'radar_dock_for_sale'},
        {id = 372, name = 'Hangar For Sale', icon = 'radar_hangar_for_sale'},
        {id = 436, name = 'Hot Property', icon = 'radar_hot_property'},
        {id = 457, name = 'Assault Package', icon = 'radar_assault_package'},
        {id = 473, name = 'Warehouse', icon = 'radar_warehouse'},
        {id = 474, name = 'Warehouse For Sale', icon = 'radar_warehouse_for_sale'},
        {id = 475, name = 'Office', icon = 'radar_office'},
        {id = 476, name = 'Office For Sale', icon = 'radar_office_for_sale'},
        {id = 478, name = 'Contraband', icon = 'radar_contraband'},
        {id = 480, name = 'Vip', icon = 'radar_vip'},
        {id = 500, name = 'Production Money', icon = 'radar_production_money'},
        {id = 501, name = 'Package', icon = 'radar_package'},
        {id = 514, name = 'Drugs Package', icon = 'radar_drugs_package'},
        {id = 527, name = 'Junkyard', icon = 'radar_junkyard'},
        {id = 557, name = 'Property Bunker', icon = 'radar_property_bunker'},
        {id = 565, name = 'Adversary Bunker', icon = 'radar_adversary_bunker'},
        {id = 569, name = 'Sm Hangar', icon = 'radar_sm_hangar'},
        {id = 614, name = 'Bat Club Property', icon = 'radar_bat_club_property'},
        {id = 628, name = 'Bat Cash Reg', icon = 'radar_bat_cash_reg'},
        {id = 779, name = 'Auto Shop Property', icon = 'radar_auto_shop_property'},
        {id = 780, name = 'Docks Export', icon = 'radar_docks_export'},
        {id = 826, name = 'Agency', icon = 'radar_agency'},
        {id = 842, name = 'Dead Drop Package', icon = 'radar_dead_drop_package'},
        {id = 847, name = 'Warehouse Juggalo', icon = 'radar_warehouse_juggalo'},
        {id = 848, name = 'Warehouse Juggalo Dax', icon = 'radar_warehouse_juggalo_dax'},
        {id = 856, name = 'Multistorey Garage', icon = 'radar_multistorey_garage'},
        {id = 857, name = 'Seized Asset Sales', icon = 'radar_seized_asset_sales'},
        {id = 872, name = 'Vinewood Garage', icon = 'radar_vinewood_garage'},
        {id = 884, name = 'Office Transporter', icon = 'radar_office_transporter'},
        {id = 900, name = 'Garment Factory', icon = 'radar_garment_factory'},
        {id = 901, name = 'Garment Factory For Sale', icon = 'radar_garment_factory_for_sale'},
        {id = 902, name = 'Garment Factory Equipment', icon = 'radar_garment_factory_equipment'},
        {id = 903, name = 'Field Hangar', icon = 'radar_field_hangar'},
        {id = 904, name = 'Field Hangar For Sale', icon = 'radar_field_hangar_for_sale'},
        {id = 919, name = 'Field Hangar Discount', icon = 'radar_field_hangar_discount'},
        {id = 920, name = 'Garment Factory Discount', icon = 'radar_garment_factory_discount'},
        {id = 925, name = 'Smoke Shop', icon = 'radar_smoke_shop'},
        {id = 926, name = 'Smoke Shop For Sale', icon = 'radar_smoke_shop_for_sale'},
        {id = 927, name = 'Smoke Shop Attention', icon = 'radar_smoke_shop_attention'},
        {id = 928, name = 'Helitours', icon = 'radar_helitours'},
        {id = 929, name = 'Helitours For Sale', icon = 'radar_helitours_for_sale'},
        {id = 930, name = 'Helitours Attention', icon = 'radar_helitours_attention'},
    }},
    {cat = 'Recreation & Activities', list = {
        {id = 82, name = 'Drag Race Finish', icon = 'radar_drag_race_finish'},
        {id = 85, name = 'Vinewood Tours', icon = 'radar_vinewood_tours'},
        {id = 90, name = 'Flight School', icon = 'radar_flight_school'},
        {id = 92, name = 'Air Hockey', icon = 'radar_air_hockey'},
        {id = 93, name = 'Bar', icon = 'radar_bar'},
        {id = 94, name = 'Base Jump', icon = 'radar_base_jump'},
        {id = 95, name = 'Basketball', icon = 'radar_basketball'},
        {id = 99, name = 'Cabaret Club', icon = 'radar_cabaret_club'},
        {id = 102, name = 'Comedy Club', icon = 'radar_comedy_club'},
        {id = 103, name = 'Darts', icon = 'radar_darts'},
        {id = 109, name = 'Golf', icon = 'radar_golf'},
        {id = 119, name = 'Shooting Range', icon = 'radar_shooting_range'},
        {id = 121, name = 'Strip Club', icon = 'radar_strip_club'},
        {id = 122, name = 'Tennis', icon = 'radar_tennis'},
        {id = 126, name = 'Triathlon', icon = 'radar_triathlon'},
        {id = 127, name = 'Off Road Racing', icon = 'radar_off_road_racing'},
        {id = 135, name = 'Cinema', icon = 'radar_cinema'},
        {id = 136, name = 'Music Venue', icon = 'radar_music_venue'},
        {id = 141, name = 'Hunting', icon = 'radar_hunting'},
        {id = 142, name = 'Pool', icon = 'radar_pool'},
        {id = 179, name = 'Triathlon Cycling', icon = 'radar_triathlon_cycling'},
        {id = 180, name = 'Triathlon Swimming', icon = 'radar_triathlon_swimming'},
        {id = 197, name = 'Yoga', icon = 'radar_yoga'},
        {id = 266, name = 'Fairground', icon = 'radar_fairground'},
        {id = 305, name = 'Horde', icon = 'radar_horde'},
        {id = 310, name = 'Deathmatch', icon = 'radar_deathmatch'},
        {id = 311, name = 'Arm Wrestling', icon = 'radar_arm_wrestling'},
        {id = 314, name = 'Race Air', icon = 'radar_race_air'},
        {id = 315, name = 'Race Land', icon = 'radar_race_land'},
        {id = 316, name = 'Race Sea', icon = 'radar_race_sea'},
        {id = 358, name = 'Golf Flag', icon = 'radar_golf_flag'},
        {id = 378, name = 'Team Deathmatch', icon = 'radar_team_deathmatch'},
        {id = 379, name = 'Race Foot', icon = 'radar_race_foot'},
        {id = 381, name = 'Barry', icon = 'radar_barry'},
        {id = 408, name = 'Capture The Flag', icon = 'radar_capture_the_flag'},
        {id = 409, name = 'Last Team Standing', icon = 'radar_last_team_standing'},
        {id = 411, name = 'Capture The Flag Base', icon = 'radar_capture_the_flag_base'},
        {id = 413, name = 'Capture The Flag Outline', icon = 'radar_capture_the_flag_outline'},
        {id = 414, name = 'Capture The Flag Base Nobag', icon = 'radar_capture_the_flag_base_nobag'},
        {id = 435, name = 'Race Stunt', icon = 'radar_race_stunt'},
        {id = 438, name = 'King Of The Castle', icon = 'radar_king_of_the_castle'},
        {id = 488, name = 'Stunt', icon = 'radar_stunt'},
        {id = 490, name = 'Stunt Premium', icon = 'radar_stunt_premium'},
        {id = 491, name = 'Adversary', icon = 'radar_adversary'},
        {id = 516, name = 'Adversary 4', icon = 'radar_adversary_4'},
        {id = 517, name = 'Adversary 8', icon = 'radar_adversary_8'},
        {id = 518, name = 'Adversary 10', icon = 'radar_adversary_10'},
        {id = 519, name = 'Adversary 12', icon = 'radar_adversary_12'},
        {id = 520, name = 'Adversary 16', icon = 'radar_adversary_16'},
        {id = 571, name = 'Race Tf', icon = 'radar_race_tf'},
        {id = 610, name = 'Acsr Race Target', icon = 'radar_acsr_race_target'},
        {id = 611, name = 'Acsr Race Hotring', icon = 'radar_acsr_race_hotring'},
        {id = 641, name = 'Arena Series', icon = 'radar_arena_series'},
        {id = 642, name = 'Arena Premium', icon = 'radar_arena_premium'},
        {id = 643, name = 'Arena Workshop', icon = 'radar_arena_workshop'},
        {id = 644, name = 'Race Wars', icon = 'radar_race_wars'},
        {id = 645, name = 'Arena Turret', icon = 'radar_arena_turret'},
        {id = 646, name = 'Arena Rc Car', icon = 'radar_arena_rc_car'},
        {id = 647, name = 'Arena Rc Workshop', icon = 'radar_arena_rc_workshop'},
        {id = 648, name = 'Arena Trap Fire', icon = 'radar_arena_trap_fire'},
        {id = 649, name = 'Arena Trap Flip', icon = 'radar_arena_trap_flip'},
        {id = 650, name = 'Arena Trap Sea', icon = 'radar_arena_trap_sea'},
        {id = 651, name = 'Arena Trap Turn', icon = 'radar_arena_trap_turn'},
        {id = 652, name = 'Arena Trap Pit', icon = 'radar_arena_trap_pit'},
        {id = 653, name = 'Arena Trap Mine', icon = 'radar_arena_trap_mine'},
        {id = 654, name = 'Arena Trap Bomb', icon = 'radar_arena_trap_bomb'},
        {id = 655, name = 'Arena Trap Wall', icon = 'radar_arena_trap_wall'},
        {id = 656, name = 'Arena Trap Brd', icon = 'radar_arena_trap_brd'},
        {id = 657, name = 'Arena Trap Sbrd', icon = 'radar_arena_trap_sbrd'},
        {id = 658, name = 'Arena Bruiser', icon = 'radar_arena_bruiser'},
        {id = 659, name = 'Arena Brutus', icon = 'radar_arena_brutus'},
        {id = 660, name = 'Arena Cerberus', icon = 'radar_arena_cerberus'},
        {id = 662, name = 'Arena Dominator', icon = 'radar_arena_dominator'},
        {id = 663, name = 'Arena Impaler', icon = 'radar_arena_impaler'},
        {id = 664, name = 'Arena Imperator', icon = 'radar_arena_imperator'},
        {id = 665, name = 'Arena Issi', icon = 'radar_arena_issi'},
        {id = 666, name = 'Arena Sasquatch', icon = 'radar_arena_sasquatch'},
        {id = 667, name = 'Arena Scarab', icon = 'radar_arena_scarab'},
        {id = 669, name = 'Arena Zr380', icon = 'radar_arena_zr380'},
        {id = 673, name = 'Rc Time Trials', icon = 'radar_rc_time_trials'},
        {id = 674, name = 'King Of The Hill', icon = 'radar_king_of_the_hill'},
        {id = 675, name = 'King Of The Hill Teams', icon = 'radar_king_of_the_hill_teams'},
        {id = 679, name = 'Casino', icon = 'radar_casino'},
        {id = 680, name = 'Casino Table Games', icon = 'radar_casino_table_games'},
        {id = 681, name = 'Casino Wheel', icon = 'radar_casino_wheel'},
        {id = 682, name = 'Casino Concierge', icon = 'radar_casino_concierge'},
        {id = 683, name = 'Casino Chips', icon = 'radar_casino_chips'},
        {id = 684, name = 'Casino Horse Racing', icon = 'radar_casino_horse_racing'},
        {id = 685, name = 'Adversary Featured', icon = 'radar_adversary_featured'},
        {id = 686, name = 'Roulette 1', icon = 'radar_roulette_1'},
        {id = 687, name = 'Roulette 2', icon = 'radar_roulette_2'},
        {id = 688, name = 'Roulette 3', icon = 'radar_roulette_3'},
        {id = 689, name = 'Roulette 4', icon = 'radar_roulette_4'},
        {id = 690, name = 'Roulette 5', icon = 'radar_roulette_5'},
        {id = 691, name = 'Roulette 6', icon = 'radar_roulette_6'},
        {id = 692, name = 'Roulette 7', icon = 'radar_roulette_7'},
        {id = 693, name = 'Roulette 8', icon = 'radar_roulette_8'},
        {id = 694, name = 'Roulette 9', icon = 'radar_roulette_9'},
        {id = 695, name = 'Roulette 10', icon = 'radar_roulette_10'},
        {id = 696, name = 'Roulette 11', icon = 'radar_roulette_11'},
        {id = 697, name = 'Roulette 12', icon = 'radar_roulette_12'},
        {id = 698, name = 'Roulette 13', icon = 'radar_roulette_13'},
        {id = 699, name = 'Roulette 14', icon = 'radar_roulette_14'},
        {id = 700, name = 'Roulette 15', icon = 'radar_roulette_15'},
        {id = 701, name = 'Roulette 16', icon = 'radar_roulette_16'},
        {id = 702, name = 'Roulette 17', icon = 'radar_roulette_17'},
        {id = 703, name = 'Roulette 18', icon = 'radar_roulette_18'},
        {id = 704, name = 'Roulette 19', icon = 'radar_roulette_19'},
        {id = 705, name = 'Roulette 20', icon = 'radar_roulette_20'},
        {id = 706, name = 'Roulette 21', icon = 'radar_roulette_21'},
        {id = 707, name = 'Roulette 22', icon = 'radar_roulette_22'},
        {id = 708, name = 'Roulette 23', icon = 'radar_roulette_23'},
        {id = 709, name = 'Roulette 24', icon = 'radar_roulette_24'},
        {id = 710, name = 'Roulette 25', icon = 'radar_roulette_25'},
        {id = 711, name = 'Roulette 26', icon = 'radar_roulette_26'},
        {id = 712, name = 'Roulette 27', icon = 'radar_roulette_27'},
        {id = 713, name = 'Roulette 28', icon = 'radar_roulette_28'},
        {id = 714, name = 'Roulette 29', icon = 'radar_roulette_29'},
        {id = 715, name = 'Roulette 30', icon = 'radar_roulette_30'},
        {id = 716, name = 'Roulette 31', icon = 'radar_roulette_31'},
        {id = 717, name = 'Roulette 32', icon = 'radar_roulette_32'},
        {id = 718, name = 'Roulette 33', icon = 'radar_roulette_33'},
        {id = 719, name = 'Roulette 34', icon = 'radar_roulette_34'},
        {id = 720, name = 'Roulette 35', icon = 'radar_roulette_35'},
        {id = 721, name = 'Roulette 36', icon = 'radar_roulette_36'},
        {id = 722, name = 'Roulette 0', icon = 'radar_roulette_0'},
        {id = 723, name = 'Roulette 00', icon = 'radar_roulette_00'},
        {id = 726, name = 'Race Open Wheel', icon = 'radar_race_open_wheel'},
        {id = 740, name = 'Arcade', icon = 'radar_arcade'},
        {id = 766, name = 'Island Party', icon = 'radar_island_party'},
        {id = 785, name = 'Street Race Series', icon = 'radar_street_race_series'},
        {id = 792, name = 'Race Organiser', icon = 'radar_race_organiser'},
        {id = 819, name = 'Music Studio', icon = 'radar_music_studio'},
        {id = 849, name = 'Weapon Crowbar', icon = 'radar_weapon_crowbar'},
        {id = 876, name = 'Race Drag', icon = 'radar_race_drag'},
        {id = 877, name = 'Race Drift', icon = 'radar_race_drift'},
    }},
    {cat = 'Weapons & Combat', list = {
        {id = 44, name = 'Bomb A', icon = 'radar_bomb_a'},
        {id = 150, name = 'Weapon Assault Rifle', icon = 'radar_weapon_assault_rifle'},
        {id = 151, name = 'Weapon Bat', icon = 'radar_weapon_bat'},
        {id = 152, name = 'Weapon Grenade', icon = 'radar_weapon_grenade'},
        {id = 153, name = 'Weapon Health', icon = 'radar_weapon_health'},
        {id = 154, name = 'Weapon Knife', icon = 'radar_weapon_knife'},
        {id = 155, name = 'Weapon Molotov', icon = 'radar_weapon_molotov'},
        {id = 156, name = 'Weapon Pistol', icon = 'radar_weapon_pistol'},
        {id = 157, name = 'Weapon Rocket', icon = 'radar_weapon_rocket'},
        {id = 158, name = 'Weapon Shotgun', icon = 'radar_weapon_shotgun'},
        {id = 159, name = 'Weapon Smg', icon = 'radar_weapon_smg'},
        {id = 160, name = 'Weapon Sniper', icon = 'radar_weapon_sniper'},
        {id = 173, name = 'Weapon Minigun', icon = 'radar_weapon_minigun'},
        {id = 175, name = 'Weapon Armour', icon = 'radar_weapon_armour'},
        {id = 322, name = 'Minigun2', icon = 'radar_minigun2'},
        {id = 349, name = 'Gas Grenade', icon = 'radar_gas_grenade'},
        {id = 415, name = 'Weapon Jerrycan', icon = 'radar_weapon_jerrycan'},
        {id = 429, name = 'Temp 1', icon = 'radar_temp_1'},
        {id = 430, name = 'Temp 2', icon = 'radar_temp_2'},
        {id = 431, name = 'Temp 3', icon = 'radar_temp_3'},
        {id = 432, name = 'Temp 4', icon = 'radar_temp_4'},
        {id = 433, name = 'Temp 5', icon = 'radar_temp_5'},
        {id = 434, name = 'Temp 6', icon = 'radar_temp_6'},
        {id = 470, name = 'Weapon Railgun', icon = 'radar_weapon_railgun'},
        {id = 486, name = 'Pickup Bomb', icon = 'radar_pickup_bomb'},
        {id = 489, name = 'Weapon Lives', icon = 'radar_weapon_lives'},
        {id = 543, name = 'Jugg', icon = 'radar_jugg'},
        {id = 624, name = 'Pickup Dtb Bomb Increase', icon = 'radar_pickup_dtb_bomb_increase'},
        {id = 625, name = 'Pickup Dtb Bomb Decrease', icon = 'radar_pickup_dtb_bomb_decrease'},
        {id = 725, name = 'Weapon Alien', icon = 'radar_weapon_alien'},
        {id = 822, name = 'Explosive Charge', icon = 'radar_explosive_charge'},
        {id = 833, name = 'Flaming Skull', icon = 'radar_flaming_skull'},
        {id = 834, name = 'Weapon Ammo', icon = 'radar_weapon_ammo'},
        {id = 880, name = 'Weapon Crate', icon = 'radar_weapon_crate'},
        {id = 881, name = 'Weapon Snowball', icon = 'radar_weapon_snowball'},
        {id = 891, name = 'Weapon Emp', icon = 'radar_weapon_emp'},
        {id = 894, name = 'Weapon Emp Mine', icon = 'radar_weapon_emp_mine'},
        {id = 921, name = 'Weapon Gusenberg Sweeper', icon = 'radar_weapon_gusenberg_sweeper'},
        {id = 922, name = 'Weapon Tear Gas', icon = 'radar_weapon_tear_gas'},
    }},
    {cat = 'Gangs & Story Characters', list = {
        {id = 66, name = 'Random Character', icon = 'radar_random_character'},
        {id = 76, name = 'Armenian Family', icon = 'radar_armenian_family'},
        {id = 77, name = 'Lester Family', icon = 'radar_lester_family'},
        {id = 78, name = 'Michael Family', icon = 'radar_michael_family'},
        {id = 79, name = 'Trevor Family', icon = 'radar_trevor_family'},
        {id = 86, name = 'Lamar Family', icon = 'radar_lamar_family'},
        {id = 88, name = 'Franklin Family', icon = 'radar_franklin_family'},
        {id = 89, name = 'Chinese Strand', icon = 'radar_chinese_strand'},
        {id = 108, name = 'Financier Strand', icon = 'radar_financier_strand'},
        {id = 112, name = 'Michael Family Exile', icon = 'radar_michael_family_exile'},
        {id = 114, name = 'Random Female', icon = 'radar_random_female'},
        {id = 115, name = 'Random Male', icon = 'radar_random_male'},
        {id = 120, name = 'Solomon Strand', icon = 'radar_solomon_strand'},
        {id = 123, name = 'Trevor Family Exile', icon = 'radar_trevor_family_exile'},
        {id = 124, name = 'Michael Trevor Family', icon = 'radar_michael_trevor_family'},
        {id = 129, name = 'Gang Mexicans', icon = 'radar_gang_mexicans'},
        {id = 177, name = 'Gang Mexicans Highlight', icon = 'radar_gang_mexicans_highlight'},
        {id = 206, name = 'Epsilon', icon = 'radar_epsilon'},
        {id = 207, name = 'Financier Strand Grey', icon = 'radar_financier_strand_grey'},
        {id = 208, name = 'Trevor Family Grey', icon = 'radar_trevor_family_grey'},
        {id = 209, name = 'Trevor Family Red', icon = 'radar_trevor_family_red'},
        {id = 210, name = 'Franklin Family Grey', icon = 'radar_franklin_family_grey'},
        {id = 211, name = 'Franklin Family Blue', icon = 'radar_franklin_family_blue'},
        {id = 212, name = 'Franklin A', icon = 'radar_franklin_a'},
        {id = 213, name = 'Franklin B', icon = 'radar_franklin_b'},
        {id = 214, name = 'Franklin C', icon = 'radar_franklin_c'},
        {id = 268, name = 'Gang Highlight', icon = 'radar_gang_highlight'},
        {id = 292, name = 'Band Strand', icon = 'radar_band_strand'},
        {id = 293, name = 'Simeon Family', icon = 'radar_simeon_family'},
        {id = 352, name = 'Martin Madrazzo', icon = 'radar_martin_madrazzo'},
        {id = 355, name = 'Devin', icon = 'radar_devin'},
        {id = 382, name = 'Dom', icon = 'radar_dom'},
        {id = 383, name = 'Maryann', icon = 'radar_maryann'},
        {id = 384, name = 'Cletus', icon = 'radar_cletus'},
        {id = 385, name = 'Josh', icon = 'radar_josh'},
        {id = 386, name = 'Minute', icon = 'radar_minute'},
        {id = 387, name = 'Omega', icon = 'radar_omega'},
        {id = 388, name = 'Tonya', icon = 'radar_tonya'},
        {id = 389, name = 'Paparazzo', icon = 'radar_paparazzo'},
        {id = 400, name = 'Abigail', icon = 'radar_abigail'},
        {id = 403, name = 'Testosterone', icon = 'radar_testosterone'},
        {id = 445, name = 'Mp Lamar', icon = 'radar_mp_lamar'},
        {id = 465, name = 'Pickup Random', icon = 'radar_pickup_random'},
        {id = 627, name = 'Bat Drone', icon = 'radar_bat_drone'},
        {id = 678, name = 'Agatha', icon = 'radar_agatha'},
        {id = 737, name = 'Zhaba', icon = 'radar_zhaba'},
        {id = 738, name = 'Gerald', icon = 'radar_gerald'},
        {id = 739, name = 'Ron', icon = 'radar_ron'},
        {id = 741, name = 'Drone Controls', icon = 'radar_drone_controls'},
        {id = 745, name = 'Winky', icon = 'radar_winky'},
        {id = 823, name = 'Deity', icon = 'radar_deity'},
        {id = 824, name = 'D Champion', icon = 'radar_d_champion'},
        {id = 828, name = 'Simeon Overlay', icon = 'radar_simeon_overlay'},
        {id = 841, name = 'Dax Overlay', icon = 'radar_dax_overlay'},
        {id = 855, name = 'Ped Gang Leader', icon = 'radar_ped_gang_leader'},
        {id = 870, name = 'Yusuf', icon = 'radar_yusuf'},
        {id = 871, name = 'Vincent', icon = 'radar_vincent'},
        {id = 892, name = 'Maude Eccles', icon = 'radar_maude_eccles'},
    }},
    {cat = 'Adversary / Special Modes', list = {
        {id = 437, name = 'Urbanwarfare Versus', icon = 'radar_urbanwarfare_versus'},
        {id = 440, name = 'Dead Drop', icon = 'radar_dead_drop'},
        {id = 558, name = 'Gr Wvm 1', icon = 'radar_gr_wvm_1'},
        {id = 559, name = 'Gr Wvm 2', icon = 'radar_gr_wvm_2'},
        {id = 560, name = 'Gr Wvm 3', icon = 'radar_gr_wvm_3'},
        {id = 561, name = 'Gr Wvm 4', icon = 'radar_gr_wvm_4'},
        {id = 562, name = 'Gr Wvm 5', icon = 'radar_gr_wvm_5'},
        {id = 563, name = 'Gr Wvm 6', icon = 'radar_gr_wvm_6'},
        {id = 564, name = 'Gr Covert Ops', icon = 'radar_gr_covert_ops'},
        {id = 566, name = 'Gr Moc Upgrade', icon = 'radar_gr_moc_upgrade'},
        {id = 567, name = 'Gr W Upgrade', icon = 'radar_gr_w_upgrade'},
        {id = 568, name = 'Sm Cargo', icon = 'radar_sm_cargo'},
        {id = 572, name = 'Sm Wp1', icon = 'radar_sm_wp1'},
        {id = 573, name = 'Sm Wp2', icon = 'radar_sm_wp2'},
        {id = 574, name = 'Sm Wp3', icon = 'radar_sm_wp3'},
        {id = 575, name = 'Sm Wp4', icon = 'radar_sm_wp4'},
        {id = 576, name = 'Sm Wp5', icon = 'radar_sm_wp5'},
        {id = 577, name = 'Sm Wp6', icon = 'radar_sm_wp6'},
        {id = 578, name = 'Sm Wp7', icon = 'radar_sm_wp7'},
        {id = 579, name = 'Sm Wp8', icon = 'radar_sm_wp8'},
        {id = 580, name = 'Sm Wp9', icon = 'radar_sm_wp9'},
        {id = 581, name = 'Sm Wp10', icon = 'radar_sm_wp10'},
        {id = 582, name = 'Sm Wp11', icon = 'radar_sm_wp11'},
        {id = 583, name = 'Sm Wp12', icon = 'radar_sm_wp12'},
        {id = 584, name = 'Sm Wp13', icon = 'radar_sm_wp13'},
        {id = 585, name = 'Sm Wp14', icon = 'radar_sm_wp14'},
        {id = 586, name = 'Nhp Bag', icon = 'radar_nhp_bag'},
        {id = 587, name = 'Nhp Chest', icon = 'radar_nhp_chest'},
        {id = 588, name = 'Nhp Orbit', icon = 'radar_nhp_orbit'},
        {id = 589, name = 'Nhp Veh1', icon = 'radar_nhp_veh1'},
        {id = 590, name = 'Nhp Base', icon = 'radar_nhp_base'},
        {id = 591, name = 'Nhp Overlay', icon = 'radar_nhp_overlay'},
        {id = 592, name = 'Nhp Turret', icon = 'radar_nhp_turret'},
        {id = 593, name = 'Nhp Mg Firewall', icon = 'radar_nhp_mg_firewall'},
        {id = 594, name = 'Nhp Mg Node', icon = 'radar_nhp_mg_node'},
        {id = 595, name = 'Nhp Wp1', icon = 'radar_nhp_wp1'},
        {id = 596, name = 'Nhp Wp2', icon = 'radar_nhp_wp2'},
        {id = 597, name = 'Nhp Wp3', icon = 'radar_nhp_wp3'},
        {id = 598, name = 'Nhp Wp4', icon = 'radar_nhp_wp4'},
        {id = 599, name = 'Nhp Wp5', icon = 'radar_nhp_wp5'},
        {id = 600, name = 'Nhp Wp6', icon = 'radar_nhp_wp6'},
        {id = 601, name = 'Nhp Wp7', icon = 'radar_nhp_wp7'},
        {id = 602, name = 'Nhp Wp8', icon = 'radar_nhp_wp8'},
        {id = 603, name = 'Nhp Wp9', icon = 'radar_nhp_wp9'},
        {id = 604, name = 'Nhp Cctv', icon = 'radar_nhp_cctv'},
        {id = 606, name = 'Nhp Turret Console', icon = 'radar_nhp_turret_console'},
        {id = 607, name = 'Nhp Mg Mir Rotate', icon = 'radar_nhp_mg_mir_rotate'},
        {id = 608, name = 'Nhp Mg Mir Static', icon = 'radar_nhp_mg_mir_static'},
        {id = 609, name = 'Nhp Mg Proxy', icon = 'radar_nhp_mg_proxy'},
        {id = 612, name = 'Acsr Wp1', icon = 'radar_acsr_wp1'},
        {id = 613, name = 'Acsr Wp2', icon = 'radar_acsr_wp2'},
        {id = 615, name = 'Bat Cargo', icon = 'radar_bat_cargo'},
        {id = 617, name = 'Bat Hack Jewel', icon = 'radar_bat_hack_jewel'},
        {id = 618, name = 'Bat Hack Gold', icon = 'radar_bat_hack_gold'},
        {id = 619, name = 'Bat Keypad', icon = 'radar_bat_keypad'},
        {id = 620, name = 'Bat Hack Target', icon = 'radar_bat_hack_target'},
        {id = 626, name = 'Bat Rival Club', icon = 'radar_bat_rival_club'},
        {id = 629, name = 'Cctv', icon = 'radar_cctv'},
        {id = 630, name = 'Bat Assassinate', icon = 'radar_bat_assassinate'},
        {id = 632, name = 'Bat Wp1', icon = 'radar_bat_wp1'},
        {id = 633, name = 'Bat Wp2', icon = 'radar_bat_wp2'},
        {id = 634, name = 'Bat Wp3', icon = 'radar_bat_wp3'},
        {id = 635, name = 'Bat Wp4', icon = 'radar_bat_wp4'},
        {id = 636, name = 'Bat Wp5', icon = 'radar_bat_wp5'},
        {id = 637, name = 'Bat Wp6', icon = 'radar_bat_wp6'},
        {id = 640, name = 'Bat Wp7', icon = 'radar_bat_wp7'},
        {id = 727, name = 'Rappel', icon = 'radar_rappel'},
        {id = 729, name = 'Scuba Gear', icon = 'radar_scuba_gear'},
        {id = 761, name = 'Bolt Cutters', icon = 'radar_bolt_cutters'},
        {id = 762, name = 'Rappel Gear', icon = 'radar_rappel_gear'},
        {id = 763, name = 'Keycard', icon = 'radar_keycard'},
        {id = 764, name = 'Password', icon = 'radar_password'},
        {id = 768, name = 'Underwater Gate', icon = 'radar_underwater_gate'},
        {id = 769, name = 'Power Switch', icon = 'radar_power_switch'},
        {id = 770, name = 'Compound Gate', icon = 'radar_compound_gate'},
        {id = 771, name = 'Rappel Point', icon = 'radar_rappel_point'},
        {id = 772, name = 'Keypad', icon = 'radar_keypad'},
        {id = 836, name = 'Cayo Series', icon = 'radar_cayo_series'},
        {id = 858, name = 'Cayo Attrition', icon = 'radar_cayo_attrition'},
        {id = 866, name = 'Signal Jammer', icon = 'radar_signal_jammer'},
        {id = 874, name = 'Cctv Workstation', icon = 'radar_cctv_workstation'},
        {id = 875, name = 'Hacking Device', icon = 'radar_hacking_device'},
    }},
    {cat = 'Pickups & Powerups', list = {
        {id = 392, name = 'Green And Net Player1', icon = 'radar_green_and_net_player1'},
        {id = 393, name = 'Green And Net Player2', icon = 'radar_green_and_net_player2'},
        {id = 394, name = 'Green And Net Player3', icon = 'radar_green_and_net_player3'},
        {id = 396, name = 'Net Player1 And Net Player2', icon = 'radar_net_player1_and_net_player2'},
        {id = 397, name = 'Net Player1 And Net Player3', icon = 'radar_net_player1_and_net_player3'},
        {id = 419, name = 'Capture The Usaflag', icon = 'radar_capture_the_usaflag'},
        {id = 420, name = 'Capture The Usaflag Outline', icon = 'radar_capture_the_usaflag_outline'},
        {id = 447, name = 'Corner Number 1', icon = 'radar_corner_number_1'},
        {id = 448, name = 'Corner Number 2', icon = 'radar_corner_number_2'},
        {id = 449, name = 'Corner Number 3', icon = 'radar_corner_number_3'},
        {id = 450, name = 'Corner Number 4', icon = 'radar_corner_number_4'},
        {id = 451, name = 'Corner Number 5', icon = 'radar_corner_number_5'},
        {id = 452, name = 'Corner Number 6', icon = 'radar_corner_number_6'},
        {id = 453, name = 'Corner Number 7', icon = 'radar_corner_number_7'},
        {id = 454, name = 'Corner Number 8', icon = 'radar_corner_number_8'},
        {id = 463, name = 'Pickup Beast', icon = 'radar_pickup_beast'},
        {id = 464, name = 'Pickup Zoned', icon = 'radar_pickup_zoned'},
        {id = 466, name = 'Pickup Slow Time', icon = 'radar_pickup_slow_time'},
        {id = 467, name = 'Pickup Swap', icon = 'radar_pickup_swap'},
        {id = 468, name = 'Pickup Thermal', icon = 'radar_pickup_thermal'},
        {id = 469, name = 'Pickup Weed', icon = 'radar_pickup_weed'},
        {id = 472, name = 'Pickup Hidden', icon = 'radar_pickup_hidden'},
        {id = 483, name = 'Pickup Accelerator', icon = 'radar_pickup_accelerator'},
        {id = 484, name = 'Pickup Ghost', icon = 'radar_pickup_ghost'},
        {id = 485, name = 'Pickup Detonator', icon = 'radar_pickup_detonator'},
        {id = 487, name = 'Pickup Armoured', icon = 'radar_pickup_armoured'},
        {id = 502, name = 'Capture 1', icon = 'radar_capture_1'},
        {id = 503, name = 'Capture 2', icon = 'radar_capture_2'},
        {id = 504, name = 'Capture 3', icon = 'radar_capture_3'},
        {id = 505, name = 'Capture 4', icon = 'radar_capture_4'},
        {id = 506, name = 'Capture 5', icon = 'radar_capture_5'},
        {id = 507, name = 'Capture 6', icon = 'radar_capture_6'},
        {id = 508, name = 'Capture 7', icon = 'radar_capture_7'},
        {id = 509, name = 'Capture 8', icon = 'radar_capture_8'},
        {id = 510, name = 'Capture 9', icon = 'radar_capture_9'},
        {id = 511, name = 'Capture 10', icon = 'radar_capture_10'},
        {id = 515, name = 'Pickup Jump', icon = 'radar_pickup_jump'},
        {id = 522, name = 'Pickup Deadline', icon = 'radar_pickup_deadline'},
        {id = 544, name = 'Pickup Repair', icon = 'radar_pickup_repair'},
        {id = 547, name = 'Pickup Rocket Boost', icon = 'radar_pickup_rocket_boost'},
        {id = 548, name = 'Pickup Homing Rocket', icon = 'radar_pickup_homing_rocket'},
        {id = 549, name = 'Pickup Machinegun', icon = 'radar_pickup_machinegun'},
        {id = 550, name = 'Pickup Parachute', icon = 'radar_pickup_parachute'},
        {id = 551, name = 'Pickup Time 5', icon = 'radar_pickup_time_5'},
        {id = 552, name = 'Pickup Time 10', icon = 'radar_pickup_time_10'},
        {id = 553, name = 'Pickup Time 15', icon = 'radar_pickup_time_15'},
        {id = 554, name = 'Pickup Time 20', icon = 'radar_pickup_time_20'},
        {id = 555, name = 'Pickup Time 30', icon = 'radar_pickup_time_30'},
        {id = 621, name = 'Pickup Dtb Health', icon = 'radar_pickup_dtb_health'},
        {id = 622, name = 'Pickup Dtb Blast Increase', icon = 'radar_pickup_dtb_blast_increase'},
        {id = 623, name = 'Pickup Dtb Blast Decrease', icon = 'radar_pickup_dtb_blast_decrease'},
        {id = 730, name = 'Cpanel 1', icon = 'radar_cpanel_1'},
        {id = 731, name = 'Cpanel 2', icon = 'radar_cpanel_2'},
        {id = 732, name = 'Cpanel 3', icon = 'radar_cpanel_3'},
        {id = 733, name = 'Cpanel 4', icon = 'radar_cpanel_4'},
    }},
    {cat = 'Cameras & Misc', list = {
        {id = 36, name = 'Cable Car', icon = 'radar_cable_car'},
        {id = 37, name = 'Activities', icon = 'radar_activities'},
        {id = 38, name = 'Raceflag', icon = 'radar_raceflag'},
        {id = 40, name = 'Safehouse', icon = 'radar_safehouse'},
        {id = 62, name = 'Assassins Mark', icon = 'radar_assassins_mark'},
        {id = 63, name = 'Elevator', icon = 'radar_elevator'},
        {id = 67, name = 'Security Van', icon = 'radar_security_van'},
        {id = 84, name = 'Rampage', icon = 'radar_rampage'},
        {id = 91, name = 'Eye Sky', icon = 'radar_eye_sky'},
        {id = 110, name = 'Gun Shop', icon = 'radar_gun_shop'},
        {id = 111, name = 'Internet Cafe', icon = 'radar_internet_cafe'},
        {id = 140, name = 'Weed Stash', icon = 'radar_weed_stash'},
        {id = 147, name = 'Arms Dealing', icon = 'radar_arms_dealing'},
        {id = 149, name = 'Celebrity Theft', icon = 'radar_celebrity_theft'},
        {id = 161, name = 'Mp Noise', icon = 'radar_mp_noise', animated = true},
        {id = 184, name = 'Camera', icon = 'radar_camera'},
        {id = 192, name = 'Camera Badger', icon = 'radar_camera_badger'},
        {id = 193, name = 'Camera Facade', icon = 'radar_camera_facade'},
        {id = 194, name = 'Camera Ifruit', icon = 'radar_camera_ifruit'},
        {id = 198, name = 'Taxi', icon = 'radar_taxi'},
        {id = 205, name = 'Shrink', icon = 'radar_shrink'},
        {id = 229, name = 'Guncar', icon = 'radar_guncar'},
        {id = 232, name = 'Driving Vagos', icon = 'radar_driving_vagos'},
        {id = 251, name = 'Arms Dealing Air', icon = 'radar_arms_dealing_air'},
        {id = 254, name = 'Playerstate Driving', icon = 'radar_playerstate_driving'},
        {id = 255, name = 'Playerstate Keyholder', icon = 'radar_playerstate_keyholder'},
        {id = 256, name = 'Playerstate Partner', icon = 'radar_playerstate_partner'},
        {id = 262, name = 'Ztype', icon = 'radar_ztype'},
        {id = 263, name = 'Stinger', icon = 'radar_stinger'},
        {id = 264, name = 'Packer', icon = 'radar_packer'},
        {id = 265, name = 'Monroe', icon = 'radar_monroe'},
        {id = 269, name = 'Altruist', icon = 'radar_altruist'},
        {id = 270, name = 'Ai', icon = 'radar_ai'},
        {id = 271, name = 'On Mission', icon = 'radar_on_mission'},
        {id = 273, name = 'Chop', icon = 'radar_chop'},
        {id = 274, name = 'Dead', icon = 'radar_dead'},
        {id = 275, name = 'Territory Locked', icon = 'radar_territory_locked'},
        {id = 279, name = 'Hooker', icon = 'radar_hooker'},
        {id = 303, name = 'Bounty Hit', icon = 'radar_bounty_hit'},
        {id = 304, name = 'Ugc Mission', icon = 'radar_ugc_mission'},
        {id = 306, name = 'Cratedrop', icon = 'radar_cratedrop'},
        {id = 309, name = 'Race', icon = 'radar_race'},
        {id = 313, name = 'Shootingrange Gunshop', icon = 'radar_shootingrange_gunshop'},
        {id = 318, name = 'Garbage', icon = 'radar_garbage'},
        {id = 319, name = 'Drill', icon = 'radar_drill'},
        {id = 320, name = 'Spikes', icon = 'radar_spikes'},
        {id = 323, name = 'Bugstar', icon = 'radar_bugstar'},
        {id = 353, name = 'Enemy Heli Spin', icon = 'radar_enemy_heli_spin', animated = true},
        {id = 354, name = 'Boost', icon = 'radar_boost'},
        {id = 360, name = 'Helipad', icon = 'radar_helipad'},
        {id = 361, name = 'Jerry Can', icon = 'radar_jerry_can'},
        {id = 362, name = 'Mask', icon = 'radar_mask'},
        {id = 364, name = 'Incapacitated', icon = 'radar_incapacitated'},
        {id = 366, name = 'Boilersuit', icon = 'radar_boilersuit'},
        {id = 367, name = 'Completed', icon = 'radar_completed'},
        {id = 368, name = 'Rockets', icon = 'radar_rockets'},
        {id = 373, name = 'Placeholder 6', icon = 'radar_placeholder_6'},
        {id = 377, name = 'Parachute', icon = 'radar_parachute'},
        {id = 390, name = 'Aim', icon = 'radar_aim'},
        {id = 391, name = 'Cratedrop Background', icon = 'radar_cratedrop_background'},
        {id = 398, name = 'Creator', icon = 'radar_creator'},
        {id = 399, name = 'Creator Direction', icon = 'radar_creator_direction'},
        {id = 402, name = 'Repair', icon = 'radar_repair'},
        {id = 405, name = 'Fanatic', icon = 'radar_fanatic'},
        {id = 407, name = 'Info Icon', icon = 'radar_info_icon'},
        {id = 418, name = 'Bounty Hit Inside', icon = 'radar_bounty_hit_inside'},
        {id = 422, name = 'Player Heli', icon = 'radar_player_heli', animated = true},
        {id = 426, name = 'Player Guncar', icon = 'radar_player_guncar'},
        {id = 439, name = 'Player King', icon = 'radar_player_king'},
        {id = 441, name = 'Penned In', icon = 'radar_penned_in'},
        {id = 442, name = 'Beast', icon = 'radar_beast'},
        {id = 444, name = 'Edge Crosstheline', icon = 'radar_edge_crosstheline'},
        {id = 446, name = 'Bennys', icon = 'radar_bennys'},
        {id = 456, name = 'Finders Keepers', icon = 'radar_finders_keepers'},
        {id = 458, name = 'Hunt The Boss', icon = 'radar_hunt_the_boss'},
        {id = 459, name = 'Sightseer', icon = 'radar_sightseer'},
        {id = 461, name = 'Belly Of The Beast', icon = 'radar_belly_of_the_beast'},
        {id = 496, name = 'Production Weed', icon = 'radar_production_weed'},
        {id = 497, name = 'Production Crack', icon = 'radar_production_crack'},
        {id = 498, name = 'Production Fake Id', icon = 'radar_production_fake_id'},
        {id = 499, name = 'Production Meth', icon = 'radar_production_meth'},
        {id = 521, name = 'Laptop', icon = 'radar_laptop'},
        {id = 523, name = 'Sports Car', icon = 'radar_sports_car'},
        {id = 525, name = 'Reg Papers', icon = 'radar_reg_papers'},
        {id = 535, name = 'Target A', icon = 'radar_target_a'},
        {id = 536, name = 'Target B', icon = 'radar_target_b'},
        {id = 537, name = 'Target C', icon = 'radar_target_c'},
        {id = 538, name = 'Target D', icon = 'radar_target_d'},
        {id = 539, name = 'Target E', icon = 'radar_target_e'},
        {id = 540, name = 'Target F', icon = 'radar_target_f'},
        {id = 541, name = 'Target G', icon = 'radar_target_g'},
        {id = 542, name = 'Target H', icon = 'radar_target_h'},
        {id = 545, name = 'Steeringwheel', icon = 'radar_steeringwheel'},
        {id = 546, name = 'Trophy', icon = 'radar_trophy'},
        {id = 556, name = 'Supplies', icon = 'radar_supplies'},
        {id = 670, name = 'Ap', icon = 'radar_ap'},
        {id = 671, name = 'Comic Store', icon = 'radar_comic_store'},
        {id = 676, name = 'Rucksack', icon = 'radar_rucksack'},
        {id = 743, name = 'Stairs', icon = 'radar_stairs'},
        {id = 744, name = 'Camera 2', icon = 'radar_camera_2'},
        {id = 751, name = 'Ship Wheel', icon = 'radar_ship_wheel'},
        {id = 753, name = 'Seasparrow2', icon = 'radar_seasparrow2'},
        {id = 756, name = 'Retro Sports Car', icon = 'radar_retro_sports_car'},
        {id = 759, name = 'Valkyrie2', icon = 'radar_valkyrie2'},
        {id = 776, name = 'Painting', icon = 'radar_painting'},
        {id = 786, name = 'Pursuit Series', icon = 'radar_pursuit_series'},
        {id = 789, name = 'Bounty Collectibles', icon = 'radar_bounty_collectibles'},
        {id = 790, name = 'Movie Collectibles', icon = 'radar_movie_collectibles'},
        {id = 793, name = 'Chalkboard List', icon = 'radar_chalkboard_list'},
        {id = 801, name = 'Construction Outfit', icon = 'radar_construction_outfit'},
        {id = 802, name = 'Overlay Jammed', icon = 'radar_overlay_jammed'},
        {id = 806, name = 'Placeholder 7', icon = 'radar_placeholder_7'},
        {id = 807, name = 'Placeholder 8', icon = 'radar_placeholder_8'},
        {id = 808, name = 'Placeholder 9', icon = 'radar_placeholder_9'},
        {id = 809, name = 'Featured Series', icon = 'radar_featured_series'},
        {id = 812, name = 'Suv Service', icon = 'radar_suv_service'},
        {id = 813, name = 'Security Contract', icon = 'radar_security_contract'},
        {id = 814, name = 'Safe', icon = 'radar_safe'},
        {id = 820, name = 'Jubilee', icon = 'radar_jubilee'},
        {id = 829, name = 'Junk Skydive', icon = 'radar_junk_skydive'},
        {id = 835, name = 'Community Series', icon = 'radar_community_series'},
        {id = 839, name = 'Acid', icon = 'radar_acid'},
        {id = 844, name = 'Gun Van', icon = 'radar_gun_van'},
        {id = 854, name = 'Acid Boost', icon = 'radar_acid_boost'},
        {id = 861, name = 'Raiju', icon = 'radar_raiju'},
        {id = 863, name = 'Overlay Ready For Sell', icon = 'radar_overlay_ready_for_sell'},
        {id = 864, name = 'Overlay Missing Supplies', icon = 'radar_overlay_missing_supplies'},
        {id = 865, name = 'Streamer216', icon = 'radar_streamer216'},
        {id = 867, name = 'Salvage Yard', icon = 'radar_salvage_yard'},
        {id = 873, name = 'Lstb', icon = 'radar_lstb'},
        {id = 885, name = 'Yankton Survival', icon = 'radar_yankton_survival'},
        {id = 886, name = 'Daily Bounty', icon = 'radar_daily_bounty'},
        {id = 887, name = 'Bounty Target', icon = 'radar_bounty_target'},
        {id = 888, name = 'Filming Schedule', icon = 'radar_filming_schedule'},
        {id = 889, name = 'Pizza This', icon = 'radar_pizza_this'},
        {id = 895, name = 'Zombie Disease', icon = 'radar_zombie_disease'},
        {id = 896, name = 'Zombie Proximity', icon = 'radar_zombie_proximity'},
        {id = 897, name = 'Zombie Fire', icon = 'radar_zombie_fire'},
        {id = 898, name = 'Animal Possessed', icon = 'radar_animal_possessed'},
        {id = 899, name = 'Mobile Phone', icon = 'radar_mobile_phone'},
        {id = 906, name = 'Chopper Lift Ammo', icon = 'radar_chopper_lift_ammo'},
        {id = 907, name = 'Chopper Lift Armor', icon = 'radar_chopper_lift_armor'},
        {id = 908, name = 'Chopper Lift Explosives', icon = 'radar_chopper_lift_explosives'},
        {id = 909, name = 'Chopper Lift Upgrade', icon = 'radar_chopper_lift_upgrade'},
        {id = 910, name = 'Chopper Lift Weapon', icon = 'radar_chopper_lift_weapon'},
        {id = 914, name = 'Shark', icon = 'radar_shark'},
        {id = 915, name = 'Fast Travel', icon = 'radar_fast_travel'},
        {id = 918, name = 'Collectible', icon = 'radar_collectible'},
        {id = 923, name = 'Dog', icon = 'radar_dog'},
        {id = 924, name = 'Bobcat Security', icon = 'radar_bobcat_security'},
        {id = 934, name = 'Attention', icon = 'radar_attention'},
        {id = 935, name = 'Alarm', icon = 'radar_alarm'},
    }},
}

-- ================= MARKER TYPES =================
-- Complete DrawMarker type list (0-43).
-- Marker image: https://raw.githubusercontent.com/citizenfx/fivem-docs/master/static/markers/<id>.png
Config.Markers = {
    {id = 0,  name = 'Upside-down Cone'},
    {id = 1,  name = 'Vertical Cylinder'},
    {id = 2,  name = 'Thick Chevron Up'},
    {id = 3,  name = 'Thin Chevron Up'},
    {id = 4,  name = 'Checkered Flag Rect'},
    {id = 5,  name = 'Checkered Flag Circle'},
    {id = 6,  name = 'Vertical Circle'},
    {id = 7,  name = 'Plane Model'},
    {id = 8,  name = 'Lost MC (Transparent)'},
    {id = 9,  name = 'Lost MC'},
    {id = 10, name = 'Number 0'},
    {id = 11, name = 'Number 1'},
    {id = 12, name = 'Number 2'},
    {id = 13, name = 'Number 3'},
    {id = 14, name = 'Number 4'},
    {id = 15, name = 'Number 5'},
    {id = 16, name = 'Number 6'},
    {id = 17, name = 'Number 7'},
    {id = 18, name = 'Number 8'},
    {id = 19, name = 'Number 9'},
    {id = 20, name = 'Chevron Up x1'},
    {id = 21, name = 'Chevron Up x2'},
    {id = 22, name = 'Chevron Up x3'},
    {id = 23, name = 'Horizontal Circle (Fat)'},
    {id = 24, name = 'Replay Icon'},
    {id = 25, name = 'Horizontal Circle (Skinny)'},
    {id = 26, name = 'Horizontal Circle Skinny (Arrow)'},
    {id = 27, name = 'Horizontal Split Arrow Circle'},
    {id = 28, name = 'Debug Sphere'},
    {id = 29, name = 'Dollar Sign'},
    {id = 30, name = 'Horizontal Bars'},
    {id = 31, name = 'Wolf Head'},
    {id = 32, name = 'Question Mark'},
    {id = 33, name = 'Plane Symbol'},
    {id = 34, name = 'Helicopter Symbol'},
    {id = 35, name = 'Boat Symbol'},
    {id = 36, name = 'Car Symbol'},
    {id = 37, name = 'Motorcycle Symbol'},
    {id = 38, name = 'Bike Symbol'},
    {id = 39, name = 'Truck Symbol'},
    {id = 40, name = 'Parachute Symbol'},
    {id = 41, name = 'Jetpack Symbol'},
    {id = 42, name = 'Sawblade Symbol'},
    {id = 43, name = 'Cube Symbol'},
}

-- ================= CHECKPOINT TYPES =================
-- Complete CreateCheckpoint type list (0-47), as documented by CitizenFX
-- (docs.fivem.net/docs/game-references/checkpoints), valid as of build 2189.
Config.Checkpoints = {
    {id = 0,  name = 'Cylinder Single Arrow'},
    {id = 1,  name = 'Cylinder Double Arrow'},
    {id = 2,  name = 'Cylinder Triple Arrow'},
    {id = 3,  name = 'Cylinder Cycle Arrow'},
    {id = 4,  name = 'Cylinder Checkerboard'},
    {id = 5,  name = 'Cylinder Wrench'},
    {id = 6,  name = 'Cylinder Single Arrow 2'},
    {id = 7,  name = 'Cylinder Double Arrow 2'},
    {id = 8,  name = 'Cylinder Triple Arrow 2'},
    {id = 9,  name = 'Cylinder Cycle Arrow 2'},
    {id = 10, name = 'Cylinder Checkerboard 2'},
    {id = 11, name = 'Cylinder Wrench 2'},
    {id = 12, name = 'Ring Single Arrow'},
    {id = 13, name = 'Ring Double Arrow'},
    {id = 14, name = 'Ring Triple Arrow'},
    {id = 15, name = 'Ring Cycle Arrow'},
    {id = 16, name = 'Ring Checkerboard'},
    {id = 17, name = 'Single Arrow'},
    {id = 18, name = 'Double Arrow'},
    {id = 19, name = 'Triple Arrow'},
    {id = 20, name = 'Cycle Arrow'},
    {id = 21, name = 'Checkerboard'},
    {id = 22, name = 'Cylinder Single Arrow 3'},
    {id = 23, name = 'Cylinder Double Arrow 3'},
    {id = 24, name = 'Cylinder Triple Arrow 3'},
    {id = 25, name = 'Cylinder Cycle Arrow 3'},
    {id = 26, name = 'Cylinder Checkerboard 3'},
    {id = 27, name = 'Cylinder Single Arrow 4 (Small)'},
    {id = 28, name = 'Cylinder Double Arrow 4 (Small)'},
    {id = 29, name = 'Cylinder Triple Arrow 4 (Small)'},
    {id = 30, name = 'Cylinder Cycle Arrow 4 (Small)'},
    {id = 31, name = 'Cylinder Checkerboard 4 (Small)'},
    {id = 32, name = 'Cylinder Single Arrow 5'},
    {id = 33, name = 'Cylinder Double Arrow 5'},
    {id = 34, name = 'Cylinder Triple Arrow 5'},
    {id = 35, name = 'Cylinder Cycle Arrow 5'},
    {id = 36, name = 'Cylinder Checkerboard 5'},
    {id = 37, name = 'Ring Single Arrow 3'},
    {id = 38, name = 'Ring Double Arrow 3'},
    {id = 39, name = 'Ring Triple Arrow 3'},
    {id = 40, name = 'Ring Cycle Arrow 3'},
    {id = 41, name = 'Ring Checkerboard 3'},
    {id = 42, name = 'Cylinder (Plain)'},
    {id = 43, name = 'Cylinder Variant 1'},
    {id = 44, name = 'Cylinder Variant 2'},
    {id = 45, name = 'Ring With Arrow'},
    {id = 46, name = 'Ring (Plane)'},
    {id = 47, name = 'Ring (Chopper)'},
}
